### ISSUE TITLE
edit live on drag drop

### ISSUE THREAD

**Issue by tushariscoolster** [MacKentoch/easyFormGenerator#10]
Form should be edited live when am making change,

For example when am adding the input box text by drag dropping,When i change the label of that specific input box, actual changes can be only see in the preview bar, But where as i should also see changes in drag drop editor,

Hope am clear :)

**Comment by MacKentoch** [comment]
hi @tushariscoolster ,

I guess you talk about drop zone here: 
![previewdraganddropway](https://cdn.rawgit.com/MacKentoch/easyFormGenerator/master/dragdropway_preview.png)

In fact, this panel is just intended to present *form layout*.

**Why no content is bound in there :**
 
Dragable controls must 
- stay small item to manipulate
- so must have fixed width/height
- must be disabled (*so that drag-drop event won't be interrupt*) 

*During early dev, I soon went to the conclusion that it would be ugly to show bound property (since very limited size)...*.

As an example, I do not show a real `rich text editor` but something that just look like a simple text editor.
Other example, a long control description or title would have to be truncated...

**But** 

If you have a nice idea in mind (or mockup/image to show) to bypass all of that without breaking constraints (size and disabled control when drag and drop), be sure I would I'm opened to all proposition :+1: .

**Comment by tushariscoolster** [comment]
@MacKentoch  i guess there is confusion between what i said and what u understood and am sorry for that. Lets consider example am draging text input to dropzone, on right click am changing its label to name xyz. The label is actully not getting change there itself. You have to go to preview tab and see label has chaged or not. See how jotform.com work. Any way good work maan.

**Comment by MacKentoch** [comment]
@tushariscoolster super nice thank you for this [link](jotform.com)!

I keep this link as a source of inspiration :+1: since there are good stuff in there.

But despite it is really cool, jot form _does not manage **multi-column forms**...
And that is where it is more delicate (*it is so rare to find one that is exactly why I created easy form generator*).

I mean : 
- when **single column**, you can have controls with different sizes, shapes — it does not matter —. It is really easier. jot form did a super nice job with a ton of customization.
- when **multiple column**, you have to normalize controls shapes (*otherwise it can become awful or horrible to manipule*). 

I keep this issue open since your request is worth. 
Right now I'm focusing optimization before going further.

Then I will step further drag and drop way.
