### ISSUE TITLE
Allowing application developer choose added form element types

### ISSUE THREAD

**Issue by srhtcn** [MacKentoch/easyFormGenerator#11]
Hi, you have a great project and it will help me solve my problem a lot, thanks! However, it will require lots of editing because I do not want to allow users to add for example rich text editor and multi choice select etc. It seems there is not way to do that without diving into code. It would be great to have such an option. Ps. not having multi-language support was another problem for me...

**Comment by MacKentoch** [comment]
Hi @srhtcn, 

You are right, it is not possible to disable controls.
To be honest it is just because I didn't think about it :sweat_smile:.

>I really like this feature (*why didn't I think about that before?*) so that I will add it (*should not take ages for that*) so that it will be possible at config step. 

By default all controls will be enabled then `if you need` (*it won't be a requirement so that the majority of users won't even have to code more than now*) will be able to tell a provider with control you want to disable.

Concerning `i18n` or `multi-language` support I keep that feature for later since it will involve more work. 
I first keep on optimizing / refactoring both version (step way and drag and drop way) before adding such features.

**Comment by srhtcn** [comment]
I see you already started doing it. It is great!
If you want I can help with the internalization process on Angular side of your project because if I managed to integrate easyFormGenerator into my project, I need to be able to change the language. I'm planning to use angular-translate as it is kind of a defacto for Angular.

**Comment by MacKentoch** [comment]
Yes I already started 
It is not a huge feature that will give a huge benefit to easy form generator.

Concerning i18n, thank you in advance for your help. 
For sure, I will need help later to translate into various languages.
I can already take care english, french and german.

For other languages, helping will just consist of creating JSON files associated to the new language.
Right now, I have to create the english one as a starter/guideline so that anyone can contribute.

>I will give more explanation later, it will be simple (I love simplicity since it gives better results :+1: ).

But I have first to go through all my html templates to pick up all that need to be translated.

In fact just a matter of time :smile:

**Comment by MacKentoch** [comment]
@srhtcn 

Easy form generator steway version : 
- controls can be disabled from config
```javascript
//disable control example :
easyFormSteWayConfigProvider.disableControl('TextInput');      
//enable control example :
easyFormSteWayConfigProvider.enableControl('TextInput');
```
- multi language support is added - [check code for how to use in this example](https://rawgit.com/MacKentoch/easyFormGenerator/master/dist/index_StepWay_As_Module.html) - (now have 'en', 'fr', 'de', and 'jp').

**Comment by srhtcn** [comment]
Thank you for implementing these features. I would like to add tr option to languages.

**Comment by MacKentoch** [comment]
Sure, I would be pleased to add turkish. 
So I need your help to translate so that I add it in easy form generator (based on that [english version](https://rawgit.com/MacKentoch/easyFormGenerator/master/src/app/stepway/i18n/local-en.json))

You will be able to see, what it is like for other language in this [directory](https://github.com/MacKentoch/easyFormGenerator/tree/master/src/app/stepway/i18n).
