### ISSUE TITLE
Need custom validations to display certain field based on some selected values

### ISSUE THREAD

**Issue by ankitprahladsoni** [MacKentoch/easyFormGenerator#19]
Hi,
I want to know if it's possible to add more validation and actions on any field.
For example, if we have a radio button as "Are you married?"
then on selection of "Yes", spouse details row should be visible, and on selection of "No", these details should hide.
Also, if we can have few fields repeat themselves, like in the case of education details of any student.

Thanks.

**Comment by MacKentoch** [comment]
Hi!

In pure angular formly (*engine behind easy form generator*) I suppose your need would be an implementation of [nested-formly-forms](http://angular-formly.com/#/example/other/nested-formly-forms).

It should be do-able, but for a single case with angular formly.

To be honest, I don't see how to create a generator for such implementation since it depends needs that aren't generic / predictable...

But don't worry, there is another solution to implement your specific need without that much difficulties. 
In your case : 
 - `yes / no check boxes` should be managed by your controller (not easy form generator)
 - `when click yes` 
   - `ng-if or ng-show` : `a first easy form generated form` (*spouse details row should be visible...*)
 - when click no 
   - `ng-if or ng-show` : `a second easy form generated form`or nothing (*spouse details row should be hidden / another form showing etc...*)

In your specific need, you will have to code a bit. 
Is that ok for you?

**Comment by ankitprahladsoni** [comment]
Hi,

Thanks for quick response, I am currently using [this](http://angular-formly.com/#/example/field-options/hide-fields) for my needs, but I just wanted to know if it is possible through easyFormGenerator. Or if this functionality of custom validations could be added to easyFormGenerator.

Many thanks.

**Comment by MacKentoch** [comment]
Nice, this way is good too :+1: 

Hope you happy coding.
