### ISSUE TITLE
Newer version of Angular UI Bootstrap

### ISSUE THREAD

**Issue by Azanamon** [MacKentoch/easyFormGenerator#22]
Hi,

Will there be an update of easyFormGenerator with a newer version of ui-bootstrap-tpls?
The latest version of UI Bootstrap don't work with easyFormGenerator.

Thanks

**Comment by MacKentoch** [comment]
Hi,

You are right it is time to evolve that.
Since around v0.14, angular bootstrap directives changed from `bs-*` to `uib-*`.
That is a nasty breakin' change but needed because of naming collision...

That being said, I will update and make a breaking change (*we are now far from 0.14 so it won't be a problem or even noticeable to anyone*).

Thank you for this issue, I forgot about that.

**Comment by Azanamon** [comment]
Thank you for your answer.

Do you know when this update will be done? week? month?
I ask this question because i would like to use esayFormGenerator in a project but i have a deadline.

Thanks

**Comment by MacKentoch** [comment]
I hope this week it is done (the sooner is the better for me too).

I can't promise since already busy in other projects.

But I have to add new control : drop zone js (updaload file : I find it so cool to have :smile: ) and this limitation of using old ui-bootstrap is a top 1 priority since you may not by the only one in demand of that update.

**Comment by MacKentoch** [comment]
### update milestone : 

`v1.2.0` just follows `v1.1.0` but has a break change 
- it will no more support old ui-bootstrap.

*This break change should have a limited impact since majority of dev are already using more up to date versions.*

Right now the last step before v1.2.0 is 
- fixing the time picker (*I guess I may have to upgrade angular formly for that, not sure*).

**Comment by MacKentoch** [comment]
omg ui-bootstrap has become a real mess with all these breaking changes....

I thought it would be easy to update datepicker but they complicated me the task.
**Sorry it take more time...**

Now I'm nearly sure I prefer material design (angular material for angular lovers), it does not run here and there while increasing versions...

**Comment by MacKentoch** [comment]
After a huge fight with ui-datepicker breaking changes, I won.

`EasyFormGenerator` `version >1.2.0` will require `ui-bootstrap` `> 0.14` (*because of breaking changes*).

Tomorrow version 1.2.0 will be published.

**Comment by ashkrishan** [comment]
@MacKentoch thanks for your efforts and getting it ready so soon. Does this version includes file uploading/dropzone?

**Comment by MacKentoch** [comment]
I'm sorry I won't be able to include file upload control in v1.2.0.

- ui-datepicker migration took me so much time (_and that was not super fun to be honest_). But it is done now.

- And I lost time with `dropzone` (not a real solution, see my comments [#20](https://github.com/MacKentoch/easyFormGenerator/issues/20#issuecomment-198938892)).

I will go on integrating the new upload control in the next version v1.2.1.

ui-bootstrap update is requested since a while so I have to release it a soon as possible to help.

**Comment by MacKentoch** [comment]
It is still not tomorrow (at least in my timezone) but new [release v1.2.0 is now available](https://github.com/MacKentoch/easyFormGenerator/releases/tag/v1.2.0)!
