### ISSUE TITLE
Really Looks excellent work, need some help

### ISSUE THREAD

**Issue by ashkrishan** [MacKentoch/easyFormGenerator#23]
Hi 

First of all it looks excellent. And thank you for sharing. I was thinking to write something like that myself but then decided to look around if solutions already existed ("why re-invent :-)") which work with formly.

**Design -** Is it possible to drop these form controls within UI bootstrap **tabs** as a multi-step form.  I know **angular-formly** can certainly do that but wondering how would I go about with **easyFormGenerator**. Is it extensible in that sense?

**Control** - Also if I want to add/extend it with additional control say File uploading, is it easy to extend?

Your pointers are much appreciated.

Kind regards,
Ash

**Comment by MacKentoch** [comment]
Hi @ashkrishan ,

Thank you I really appreciate your feedback.

I created `easyFormGenerator` exactly because I found no UI over nice `angular formly` that suited my needs. More precisely, I wanted to be able to create at lest 2 columns per rows of controls in my form.

To be honest I did not plan at the beginning to make it open source (*it was at the beginning a simple part of a personal private project*).
Then talking with the main contributor to `angular formly`, I felt like it would be super nice to share it.

That being said it is time to answer your questions :smile:  

**Design :**

It is not that easy to modify easyFormGenerator general template (*I mean like `step way`one versus `drag and drop way` one*). It could be improved but I need to refactor more common modules to make it easier.

**_But and at least I already added some customization like_**

- `show/hide preview panel` or just `preview model` : 
```javascript 
// your own application here :
 angular
    .module('appDemo', [
      'eda.easyformGen.stepway' //injects easy form generator-step way
    ])
    .config(configFct)
    .controller('demoController', demoController);

  /**
    * config
    */
  configFct.$inject = ['easyFormSteWayConfigProvider'];
  function configFct(easyFormSteWayConfigProvider){
    //show/hide preview panel => default is true
    easyFormSteWayConfigProvider.showPreviewPanel(true);
    //show/hide models in preview panel => default is true
    easyFormSteWayConfigProvider.showPreviewModels(true);
  }
```

- `filter` over **already defined in easyFormGenerator** controls you want your form to be able to have : 

```javascript
angular
  .module('YOURAPP', ['...'])
  .config(easyFromConfigFct);

//inject easyFormSteWayConfigProvider
easyFromConfigFct.$inject = ['easyFormSteWayConfigProvider'];
function easyFromConfigFct(easyFormSteWayConfigProvider){

  //disable basic TextInput:
  easyFormSteWayConfigProvider.disableControl('TextInput');

  //enable Date input:
  //(NOTE: by default all controls are enabled
  //-> so this example is no other use than illustration)
  easyFormSteWayConfigProvider.enableControl('Date');

  // List of all easy form generator (step way version) controls:  
  // 'empty'
  // 'Header'
  // 'TextInput'
  // 'Password'
  // 'Date'
  // 'Texarea'
  // 'RichTextEditor'
  // 'Radio'
  // 'Checkbox'
  // 'BasicSelect'
  // 'GroupedSelect'
```

**angular formly :**

As for general template, adding a new control (*despite it is easier than customizing whole easyFormGenrator template*) is not now simple like updating a config function.

I still need to make it by hand since I have 2 steps : 
 - declaring template in configProvider [here](https://github.com/MacKentoch/easyFormGenerator/tree/master/src/app/stepway/components/edaStepWayEasyFormGen/config/formly)

- AND adding easyFormGenerator popup (*the one to edit control before adding to form*)

   - [here step way - not optimized since all controls in same html template](https://github.com/MacKentoch/easyFormGenerator/blob/master/src/app/stepway/components/edaStepWayEasyFormGen/modal/edaStepWayEasyFormGen.editControlModal.template.html)

   - [here drag drop way - a bit better since template separated in different directives/html templates](https://github.com/MacKentoch/easyFormGenerator/blob/master/src/app/dragdropway/components/leftPanel/edaDragDropWay.leftPanel.template.html)

**Adding Controls (related to previous)  :**

As I said I still need to add by myself even if angular formly is capable of unlimited things.

Good news is I'm working on the next version which contains 

 - a drag and drop controls [dropzone js](https://github.com/MacKentoch/easyFormGenerator/issues/20#issuecomment-192640402)

- and will work with ui Bootstrap > ~0.14 (_I mean from when UI Bootstrap directives naming convention changed from bs-* to uib-*_)

**Comment by ashkrishan** [comment]
Very helpful. Thank you for finding time to reply to my queries, really appreciated. I can imagine how hard it is to maintain an open source project with the busy schedule. I'll do my best to contribute to the project as I believe this is something undoubtedly needed in today's Angular scene, especially when you think forms are something integral to the web development and to my surprise not many quality open source form generator like yours exist out there. This is the first form generator I have seen which ticks most boxes for me. 

I am very excited by upcoming features in your new version. File uploading with drop zone would be perfect for my needs, thank you in advance!

As a developer it is not an issue for me to hand write formly code but forms in my app would be created by admin users. Hence, the need for extending the control for file uploading, looking forward to the next version.

Thank you again for all the hard work you are doing!

Regards,
Ash
