### ISSUE TITLE
Js Error

### ISSUE THREAD

**Issue by Azanamon** [MacKentoch/easyFormGenerator#25]
Hi

In the release v1.2.0 i have a js error:
- Run index_DragDropWay.html
- Right click on an element (ex: Header). Properties appear.
- Right click on the same element to hide properties. Properties disappear.
- Right click on the same element, an js error occurs:

angular.js:13283 TypeError: Cannot set property 'toggle' of undefined
    at edaDragDropWay.edaDragdropWayEasyFormGen.controller.js:364
    at angular.js:18808
    at e (angular.js:5825)
    at angular.js:6102

Thanks

**Comment by MacKentoch** [comment]
Hi @Azanamon ,

`drag And drop way` version is beta and not actively maintained like step way.
Sorry I wasn't clear in v1.2.0 release: I did not take care of drag and drop for ui-bootstrap break changes compatibility. 
I focus on production ready module `step way` and `form viewer`.
>I do not recommend to use drag and drop way. As I mention in README it is just a beta.

**If you insist on using drag and drop, you can:**
- use ui-bootstap <=v0.13.0 — not the latests versions 
- or go back previous version of drag and drop (v1.1.1) way since updating ui bootstrap implies a lot of fix that did not happen in drag and drop.


*Or even better:  pull request updates on drag and drop to support latest ui-bootstrap*.

Drag and drop is nice looking at a first sight but it offers less cross browser compatibilities. 
I even think it should need to restart from scratch and better use `dragula`. 
*But It is time consuming I can't maintain all alone with QUALITY* —I do this in free time like a majority of open source dev—

>So I focus on `step way` and `form viewer` since they are robust, production ready and cross browser. They just need few other improvements like being able to dynamically add new control (working on it, it will take time).

I guess I will split this drag and drop in another repository to avoid confusion.
