### ISSUE TITLE
Add Custom Translations

### ISSUE THREAD

**Issue by pvanhemmen** [MacKentoch/easyFormGenerator#28]
Is it possible to add custom translations to the easyFormSteWayConfigProvider? I know that I can edit eda.stepway.js and change the language config in there, but I wonder if there is a better way to add/edit custom translations myelf.

Thanx a lot!

**Comment by MacKentoch** [comment]
Hi @pvanhemmen there no way to dynamically add new translation.

Behind the scene I use `Pascal Precht's angular translate`. 
Angular translate is not designed so that you change your translation during runtime. 
it would require something like [asynchronous-loading](https://angular-translate.github.io/docs/#/guide/12_asynchronous-loading) but it would be too much.


As you already know you can switch translations in your config or in your controller but this switch is limited to already existing languages.

If you need a new language I would be pleased to add it.
