### ISSUE TITLE
Building from src

### ISSUE THREAD

**Issue by andrewfam** [MacKentoch/easyFormGenerator#39]
Hi, 

I'm trying to build the drag and drop from src so that I can extend it by adding in 3 fields plus more description fields. My dev says that some of the core files are encrypted. can you help?

Would you be able to give me a "install guide" so that I can install git source in the local.

**Comment by MacKentoch** [comment]
Hi @andrewfam 

First let me remind you that `drag and drop` is just beta.
So it is super nice for production.
But you are absolutely free to use or adapt it on your own.

If you want to use src, check `gulpfile.babel.js`:
```javascript

 /* INFO on relevant tasks :
 * -------------------------
 *
 * 1) want to build "only app dependencies"" (only), use :
 * - $ gulp
 * - $ gulp watch
 *
 * 2) want to build "all dependencies" (vendor + app), use :
 * - $ gulp build:all
 *
 * 3) want to dist, use :
 * - $ gulp dist
*/
```

Code is in ES6, so it is transpired into ES5 but not encrypted 😄 .
ES5 transpire is not human readable but for today navigator.

After updating src, use command `gulp dist` then check resulting files in `dist directory`.

**Comment by andrewfam** [comment]
thanks for this. I'll try it out. Understand its beta.
The UI could be improved on. I'm getting someone to add buttons for settings and delete on hover over instead of the current way of double clicks and right clicks. Makes it more reliable

**Comment by MacKentoch** [comment]
Awesome!

When you have results I would be pleased to know about.

I will update `stepway` to make *services* easier to maintain. 
So it will help both `drag and drop` and `stepway` (common sources).

**Comment by MacKentoch** [comment]
I have to update my answer since recent `tsunami update` in easyFormGenerator.

**I left:**
- bower
- gulp
- jspm

**in favour of just:**
- webpack

*It make things far more simple to maintain with just webpack.*

**So if you want to build**
1. ensure you have `NodeJS 6+ minimum` (*use nvm if you need to switch Node versions*)
2. builds are for dev (= no minification):
  - `npm run build-dev-stepway`
  - `npm run build-dev-formviewer`
  - `npm run build-dev-dragdropway`
3. builds are for prod:
  - `npm run build-prod-stepway`
  - `npm run build-prod-formviewer`
  - `npm run build-prod-dragdropway`

**Comment by frankV** [comment]
@MacKentoch would you accept a PR that added this info to the README? I think build/test docs would be a great add.

**Comment by MacKentoch** [comment]
@frankV Sure! You are right it would be helpful.
