### ISSUE TITLE
Help wanted on using easyFormGenerator

### ISSUE THREAD

**Issue by poraisO** [MacKentoch/easyFormGenerator#40]
Hello Kentoch,
I am from a web programmer from Netherlands.
Firstly, thanks for your efforts on easyFormGenerator.
While using your plugin, I have a question about it.
Could you please make any possible to add/remove a control from this Form?
Currently, this form has a feature to remove controls line by line.
As an experience developer, if you agree, then I will also contributes some codes for it.
By the way, I am newbie to this code, and I am not sure where to start working to add the features.
In more detail, when hovering an object (text or select...), I would like to display 2 buttons(Remove, Settings), but I don't know how to add the buttons.

Could you please give me a hint so that I can contribute your project "easyFormGenerator" ?

Looking forward to hearing from you soon.

Warmest Regards,
Polaris O.

**Comment by MacKentoch** [comment]
Hi @poraisO 

To be honest I don't give much time to easy form generator since months (tons of other projects).

Last version (not finished, need to fix a little bug before) I attempted to refactor more than before the code and I `use and abuse` **Angular js 1.5+** `component` to make it more simple to maintain.

Components way is nice, it makes things easier to read and split code into small clever components.

There are lots of things I'd like (if I had the time) to do:
- drop `jspm` in favour of `webpack` (*so that I also drop `bower` and `gulp`: babel 6 came later and simplified ES6 processing and project workflows*).
- add tests, CI
- refactor services (*I should use some kind `redux` or `rxjs` to make it easier to maintain — with new fresh eyes it is a real mess to follow: these way to manage store did not exist before...*).

**Comment by MacKentoch** [comment]
Some news.

If you want to play with src see [my comment in #39](https://github.com/MacKentoch/easyFormGenerator/issues/39#issuecomment-269893483)

**Comment by MacKentoch** [comment]
v2.1.0 is now released in npm.

Now still some refactoring to do but it is far better than a week ago.
