### ISSUE TITLE
returnSaveEvent is missing 'vm'

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#44]
Hi!

I found another issue [here](https://github.com/MacKentoch/easyFormGenerator/blob/master/public/js/eda.stepway.js#L1221)

In  `scope.returnSaveEvent = false;` You need to add `vm` to make it works. 

It should be `scope.vm.returnSaveEvent = false;`

Thanks for this awesome directive!

**Comment by MacKentoch** [comment]
Thanks I'll check this.

By the way, to simplify reading you should read the corresponding [source here](https://github.com/MacKentoch/easyFormGenerator/blob/master/src/app/stepway/components/main/stepway.main.directive.js#L53) rather than transpiled (your link).

When in production, it will be minified so it will even more obscure for human reading. Even not minified it is not easy to read.
