### ISSUE TITLE
Inject error while using 'eda.easyformGen.stepway'

### ISSUE THREAD

**Issue by darshik** [MacKentoch/easyFormGenerator#50]
getting inject error when tyring to inject 'eda.easyformGen.stepway' into my webapp. any other way to inject? I have used angular smartadmin to build my webapp. I have registered the dependencies in the vendor and have it declared in apps.js too. It doesn't  recognize the HTML tags that are to be used for using easy form generator.

**Comment by MacKentoch** [comment]
Hi @darshik 

Sorry you are in trouble. 

Let me sum up to be sure I'm not wrong in my understandings:
- you use an angular template smartadmin (*nice choice by the way it looks nice*)
- you added dependencies in `vendor` (**I guess in smartadmin vendor file?**)

1. *Do you have more information on the issue (you may already know you can follow successive error links until angular website shows the origin of the issue)?*

2. *I don't know this template sources, but could you try to use vendors from [easyFormGenerator dist directory](https://github.com/MacKentoch/easyFormGenerator/tree/master/dist/vendors) to be sure it not not due to vendors versions*

I'm sorry I have to ask you more information.
But as I don't know this template sources it is nearly impossible to guess what exactly happens.

**Comment by darshik** [comment]
Hi @MacKentoch 

I am glad to see the bunch of changes you have pushed. Great work there. 

Coming to my error, thanks for your suggestion to point to vendor in easy-form-generator. I changed reference of my angular to point it to the one provided in easy-form-generator and it resolved the inject error. However, I am still getting a bunch of other errors which stops my webapp to run. Trying a few other things and hope it resolves.

**Comment by darshik** [comment]
<img width="961" alt="screen shot 2017-01-05 at 9 50 58 am" src="https://cloud.githubusercontent.com/assets/9450985/21691246/a31bf270-d32c-11e6-930e-c55c1be2ae70.png">

**Comment by darshik** [comment]
These are the errors I am getting after pointing to the angular provided in easy-form-generator's vendor

**Comment by MacKentoch** [comment]
At 1st sight, it looks like some kind conflict between dependencies.

It seems like a provider (*because I can read `$get`*) does not like that...

Difficult to tell more from here.

But I can blindly suggest/hint: 
- be sure not to manually import angular formly (*I guess it is not the problem in your case*)
- be sure AngularJS is not loaded twice (*I guess it may not be the case*)
- downgrade AngularJS version to a 1.5.x and test it

*Really difficult for me to give more tips. I don't know your template toolchain and dependencies already used (maybe some dislike angular formly?).*

**Comment by darshik** [comment]
Okay, so I figured out the problem. Smartadmin supports only upto angular version 1.4.8. Can we work a way out to make easy form generator work with angular 1.4.x? Even if it is older version of easy-form-generator, it should be fine.

**Comment by MacKentoch** [comment]
Finally it is not an easyFormGenerator issue.

I close this issue.

Feel free to give a feedback when you succeed in solving your issue.
