### ISSUE TITLE
importing easy-form-generator

### ISSUE THREAD

**Issue by vinnybod** [MacKentoch/easyFormGenerator#55]
I am using webpack for an application and attempting to import easy-form-generator into a module.

I have the lines
```
import 'easy-form-generator/dist/eda.stepway';
import 'easy-form-generator/dist/eda.easyFormViewer';
```

and the module export includes 
```
angular.module(MODULE_NAME, ['eda.easyformGen.stepway', 'eda.easyFormViewer']
```
(there are some other modules imported as well, but i left them out to make it clearer)

Ultimately I end up with an error that looks like this:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module App due to:
Error: [$injector:modulerr] Failed to instantiate module App.review due to:
Error: [$injector:modulerr] Failed to instantiate module eda.easyformGen.stepway due to:
Error: [$injector:modulerr] Failed to instantiate module edaStepWayEasyFormGen.core due to:
Error: [$injector:modulerr] Failed to instantiate module textAngular due to:
Error: [$injector:nomod] Module 'textAngular' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
If I manually add the import `import 'easy-form-generator/dist/vendors/js/textAngular.min';` then it asks for toaster, etc, etc. 
```
Error: [$injector:modulerr] Failed to instantiate module pascalprecht.translate due to:
```

Is there a way to import all the vendor scripts easily? I noticed at https://github.com/MacKentoch/easyFormGenerator/issues/27 you mentioned being able to just use the one import statement.

**Comment by MacKentoch** [comment]
Hi,

I guess vendors need to be imported.

I left them outside easyFormGenerator bundle since it would have side effects some applications already using them.

The vendors needed:
- bootstrap (css/ jquery)
- bootswatch (nice theme)
- jquery
- angular js (>= 1.3.X dev/tested)
- ngAnimate + animate.css
- textAngular (for rich text editor)
- angular translate
- nya-bootstrap-select (for basic and grouped select)
- angular toaster (nice toaster messages)

So add them to your project:
```bash 
npm i --save bootstrap bootswatch jquery  angular angular-animate angular-translate angularjs-toaster textangular @lordfriend/nya-bootstrap-select
```

and import them in your entry js or a vendor js so that webpack will include them:
```javascript
import '@lordfriend/nya-bootstrap-select';
import 'angular';
import 'angular-animate';
import 'angular-translate';
import 'angularjs-toaster';
import 'bootstrap';
import 'bootswatch';
import 'jquery';
import 'textangular';
```

**Comment by MacKentoch** [comment]
Thanks to your issue I updated [README](https://github.com/MacKentoch/easyFormGenerator#dependencies) to make it clearer.

As no feedback, I guess it is ok. So I close this issues.

Open it back if needed.

**Comment by vinnybod** [comment]
I did get it working for the most part. I'll write up an update post describing the process in the next day.

**Comment by vinnybod** [comment]
Note: I am trying to use easyFormGenerator as a component in a larger existing project, not standalone.

So the imports ended up looking a little more like this. TextAngular needed its own ngSanitize and Bootswatch had to be imported in a different way.
```
import 'textangular/dist/textangular-sanitize.js';
import 'angularjs-toaster';
import 'angular-translate';
import 'textangular';
import 'angular-ui-bootstrap';
import '@lordfriend/nya-bootstrap-select';
import '../main.less'
import 'easy-form-generator/dist/eda.stepway';
import 'easy-form-generator/dist/eda.easyFormViewer';
```
The Bootswatch theme needed to be imported in its own less file (I called it main.less)
```
@import '~bootstrap/less/bootstrap.less';
@import '~bootswatch/paper/variables.less';
@import '~bootswatch/paper/bootswatch.less';
```

I also needed to use less-loader for the above
```
{
      test: /\.less$/,
      loader: 'style-loader!css-loader!less-loader'
      // loader: ExtractTextPlugin.extract('style-loader', 'css-loader!less-loader')
    }
```
ui.bootstrap needed to be passed into the module
```
angular.module(MODULE_NAME, ['eda.easyformGen.stepway', 'eda.easyFormViewer', 'ui.bootstrap']
```

For the most part, everything looks good! But it seems like there's some css that is interfering with the rest of the application. There is padding and margins added to the body of the app, making things appear pretty weird. Is there an easy way to remove this?
@MacKentoch

**Comment by MacKentoch** [comment]
@vinnybod thank you for this amazing complete and rich feedback :+1:

I did not have a try with webpack since my tsunami update...
You are right I forgot ngSanitize and all bootstrap , bootswatch imports...

> To sum up, I was totally inaccurate :sweat_smile:

Adding `less loader` in webpack is nice solution thank you for sharing it.
Another alternative (*not saying it is better since it doesn't make any difference it does the same*):
```javascript
// index.js of the application
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap/dist/js/bootstrap.min.js';
```

Concerning `ui-bootstrap` I'm :astonished: (*astonished*) since it is already injected in [easyFormGenerator here](https://github.com/MacKentoch/easyFormGenerator/blob/master/src/app/stepway/core/core.module.js#L9).
Maybe It is a matter of versions? 
Anyway, I don't understand you should be free from having to inject it for easy form generator. 

Finally concerning ugly margins: I'm sorry about that it my fault I embedded easyFormGenerator style into same bundle as JS part. See [#49](https://github.com/MacKentoch/easyFormGenerator/issues/49#issuecomment-270292498) It is already fixed in master branch (*not published to npm right now*).  Your style will be able override easyFormGenerator one.

**Comment by vinnybod** [comment]
I was able to override the styles by adding custom styles to my body tag
```
<body style="padding-top:0px; background-color:#ffffff; margin:0px">
```

I'll look into removing ui-bootstrap from the module to see if it makes a difference. I do think that you still need less loader because the bootswatch themes are in less

**Comment by MacKentoch** [comment]
So less loader is the best way to go.
It offers another advantage, you can edit less style source if you need.

I just thought bootswatch had already css versions in some dist dir.

**Comment by vinnybod** [comment]
I see .less and .scss

**Comment by MacKentoch** [comment]
Yes you are right.

Now I remember now I just go to bootswatch website select my theme and download css (min version) from [there for example](https://bootswatch.com/yeti/bootstrap.min.css)

My way is a bit manual...
