### ISSUE TITLE
Add an option for validation.

### ISSUE THREAD

**Issue by majortom64** [MacKentoch/easyFormGenerator#6]
This is a great start and has already benefited a project for a non-profit I am helping (I was able to layout a form that I could pass to our volunteer developers). I'd like to suggest that you add the option to specify validation options for fields. Even if you only supported the basics: email, number, URL, pattern and maybe min/max. it would be great.

As an advanced option, allowing the addition of an error message for fields that do not validate would be great.

**Comment by MacKentoch** [comment]
Thank you, for your feedback.

What you need is already planned. It is just core features or **angular formly** that would be nice in **easy form generator**.

Now, I guess that I may change my previous plans. 
I mean, I may give a little break to [drag and drop way](https://rawgit.com/MacKentoch/easyFormGenerator/master/indexDragDrop.html). 

Later (I mean today) I will check what I will fast add so that it will help you and your project.

**Comment by MacKentoch** [comment]
@majortom64 How much time do you still have before ending your project?

I'd like to finish drag and drop first since it is nearly done (_not all finished and refactored but demo-able_).

It is a shame I did not have time to refactor, so even it is not hard to add validation option it may cost a bit time.

____
_By the way, I labelled this issue as **enhancement** since it is._

**Comment by MacKentoch** [comment]
@majortom64 Hi, 

I'm currently adding validation and validation messages (*it is not finished but won't takes years*).

## As an example
Please [check here](https://rawgit.com/MacKentoch/easyFormGenerator/master/index.html) new control `email` with `validation messages` on :
 - `email pattern` validation
 - required field (if set)

## Important 

Easy form generator is now evolving 
- so **please wait few days** —*maybe tomorrow? (don't worry, I will announce it)*— (time I finish adding validation on existing controls)
- **BEFORE updating to lastest version**

## NEW : EASY FORM GENERATOR GITTER

Easy form generator has now a dedicated bitter room : [![Join the chat at https://gitter.im/MacKentoch/easyFormGenerator](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/MacKentoch/easyFormGenerator?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

*Please better use this room to give me all your suggestions that are welcomed and help me to improve easy form generator* : 
- new control?
- customize option (min, max) 
- etc...


## to finish :

> **easy form generator is yours** so don't hesitate to influence its evolution :+1:
