### ISSUE TITLE
Password input as plain text in Drag and drop way

### ISSUE THREAD

**Issue by Sunny-node** [MacKentoch/easyFormGenerator#62]
In drag and drop way, when we type in the password field in the Preview tab, it is behaving as input type text not password.

**Comment by MacKentoch** [comment]
Hi @Sunny-node,

To be honest it makes months since I did not even have a look in drag drop way version.
I focus on stepway + formviewer since they work better and are up to date.

Drag drop version is a beta that have so many issues in term of performance and cross browser compatibility.

I don't recommend to use it.
